In [20]:
import math
import cv2
import numpy as np 
from time import time
import mediapipe as mp 
import matplotlib.pyplot as plt

In [42]:
class PoseDetection():
    def __init__(self, input_path):
        self.input = input_path
        return None
    
    def detect_image(input_image_path):

        mp_pose = mp.solutions.pose
        pose = mp_pose.Pose(static_image_mode=True, min_detection_confidence = 0.3, model_complexity=2)
        mp_drawing = mp.solutions.drawing_utils

        
        input_image = cv2.imread(input_image_path)
        results = pose.process(cv2.cvtColor(input_image,cv2.COLOR_BGR2RGB))

        landmark_points = {}

        if results.pose_landmarks:
            for i in range(32):

                landmark_points[i] = {i: 
                                        {
                                            "name": mp_pose.PoseLandmark(i).name,
                                            "x": results.pose_landmarks.landmark[mp_pose.PoseLandmark(i).value].x,
                                            "y": results.pose_landmarks.landmark[mp_pose.PoseLandmark(i).value].y,
                                            "z": results.pose_landmarks.landmark[mp_pose.PoseLandmark(i).value].z
                                        }
                                        }

        # return output_image, landmark_points
        return landmark_points

    def process_landmarks(self, imageIn):

        mp_pose = mp.solutions.pose
        pose = mp_pose.Pose(static_image_mode=True, min_detection_confidence = 0.3, model_complexity=2)
        mp_drawing = mp.solutions.drawing_utils
        results = pose.process(cv2.cvtColor(imageIn,cv2.COLOR_BGR2RGB))

        landmark_points = {}

        if results.pose_landmarks:
            for i in range(32):

                landmark_points[i] = {i: 
                                        {
                                            "name": mp_pose.PoseLandmark(i).name,
                                            "x": results.pose_landmarks.landmark[mp_pose.PoseLandmark(i).value].x,
                                            "y": results.pose_landmarks.landmark[mp_pose.PoseLandmark(i).value].y,
                                            "z": results.pose_landmarks.landmark[mp_pose.PoseLandmark(i).value].z
                                        }
                                        }

        # return output_image, landmark_points
        return landmark_points

    def detect_image_test(self):

        input_image = cv2.imread(self.input)

        lp = self.process_landmarks(input_image)

        return lp

    def detect_video(self):
        
        vcap = cv2.VideoCapture(self.input)

        if (vcap.isOpened() == False): raise IsADirectoryError("File does not exist or error on loading video")

        ret, frame = vcap.read()

        cv2.imshow('video',frame)

        return frame

    def lo(self):

        out = cv2.imread(self.input)
        
        return out

In [43]:
a = "videos/sample_img.jpeg"
b = PoseDetection(input_path_2)
c = b.lo()

print(c)

{0: {0: {'name': 'NOSE', 'x': 0.4094741940498352, 'y': 0.17661041021347046, 'z': -0.6862496137619019}}, 1: {1: {'name': 'LEFT_EYE_INNER', 'x': 0.4082598388195038, 'y': 0.1580463945865631, 'z': -0.7061542868614197}}, 2: {2: {'name': 'LEFT_EYE', 'x': 0.4176032245159149, 'y': 0.1530049592256546, 'z': -0.7070907950401306}}, 3: {3: {'name': 'LEFT_EYE_OUTER', 'x': 0.42633527517318726, 'y': 0.14826741814613342, 'z': -0.7069729566574097}}, 4: {4: {'name': 'RIGHT_EYE_INNER', 'x': 0.37762948870658875, 'y': 0.1651732623577118, 'z': -0.6679149270057678}}, 5: {5: {'name': 'RIGHT_EYE', 'x': 0.3659151792526245, 'y': 0.1653871089220047, 'z': -0.6695122718811035}}, 6: {6: {'name': 'RIGHT_EYE_OUTER', 'x': 0.3546685576438904, 'y': 0.16542376577854156, 'z': -0.67067551612854}}, 7: {7: {'name': 'LEFT_EAR', 'x': 0.45634108781814575, 'y': 0.1209365576505661, 'z': -0.5509464144706726}}, 8: {8: {'name': 'RIGHT_EAR', 'x': 0.3578430116176605, 'y': 0.14853018522262573, 'z': -0.3706682324409485}}, 9: {9: {'name': 

## Testing singular image

In [40]:
input_path_2 = "videos/sample_img.jpeg"
test_2 = PoseDetection(input_path_2)

lp_2 = test_2.detect_image_test()

In [41]:
print(lp_2[1])

{1: {'name': 'LEFT_EYE_INNER', 'x': 0.4082598388195038, 'y': 0.1580463945865631, 'z': -0.7061542868614197}}


In [32]:
print(lp_2[1][1]['name'])
print(lp_2[1][1]['x'])
print(lp_2[1][1]['y'])
print(lp_2[1][1]['z'])

LEFT_EYE_INNER
0.4082598388195038
0.1580463945865631
-0.7061542868614197


## Testing Video

In [39]:
video_test_path = "videos/my_swing.mp4"
video_test = PoseDetection(video_test_path)

video_out = video_test.detect_video()

print(video_out[1])

[[ 52  33  16]
 [ 49  31  13]
 [ 75  56  39]
 ...
 [192 143 113]
 [194 145 116]
 [195 146 117]]
